#!/bin/bash
set -euo pipefail
##########################################################
# aider Installation - CCC CODE Pattern
##########################################################

source /etc/ccc.conf
source /root/ccc/setup/functions.sh

echo -e "${BLUE}[MODULE]${NC} Aider Installation (CCC CODE Style)..."

# Aider Configuration in Storage Root
AIDER_DIR="$STORAGE_ROOT/tools/aider"
AIDER_CONFIG="$STORAGE_ROOT/config/aider"

# Verzeichnisse erstellen
mkdir -p "$AIDER_DIR"
mkdir -p "$AIDER_CONFIG"
chown -R "$STORAGE_USER:$STORAGE_USER" "$AIDER_DIR" "$AIDER_CONFIG"

# Systemweite Voraussetzungen mit idempotenter Funktion
install_package python3 python3-pip python3-venv git curl wget

# Python Virtual Environment für Aider erstellen (idempotent)
if [ ! -f "$AIDER_DIR/bin/activate" ]; then
    log_info "Erstelle Python Virtual Environment..."
    sudo -u "$STORAGE_USER" python3 -m venv "$AIDER_DIR"
else
    log_info "Python Virtual Environment existiert bereits"
fi

# Aider im Virtual Environment installieren/updaten
log_info "Installiere/Update Aider..."
sudo -u "$STORAGE_USER" bash -c "
    source '$AIDER_DIR/bin/activate'
    pip install --upgrade pip
    pip install --upgrade aider-chat
    pip install --upgrade python-dotenv
"

# OpenRouter Konfiguration
if [ ! -f "$AIDER_CONFIG/openrouter-api-key" ]; then
    log_info "OpenRouter Konfiguration..."
    
    # Falls API Key als Umgebungsvariable existiert
    if [ -n "$OPENROUTER_API_KEY" ]; then
        echo "$OPENROUTER_API_KEY" > "$AIDER_CONFIG/openrouter-api-key"
        chmod 600 "$AIDER_CONFIG/openrouter-api-key"
        log_success "OpenRouter API Key aus Umgebungsvariable übernommen"
    else
        log_warning "Kein OpenRouter API Key konfiguriert"
        echo "# Füge hier deinen OpenRouter API Key ein" > "$AIDER_CONFIG/openrouter-api-key"
        log_info "Bitte trage deinen OpenRouter API Key in $AIDER_CONFIG/openrouter-api-key ein"
    fi
fi

# Aider Konfigurationsdatei erstellen
cat > "$AIDER_CONFIG/aider.conf" << AIDERCONF
# Aider Configuration - Generated by CCC
# Storage: $AIDER_CONFIG

# OpenRouter Configuration
export OPENROUTER_API_KEY=\$(cat $AIDER_CONFIG/openrouter-api-key 2>/dev/null || echo "")

# Default Model
export AIDER_MODEL=openrouter/anthropic/claude-3.5-sonnet

# Aider Virtual Environment
export AIDER_VENV=$AIDER_DIR
AIDERCONF

# Globales Aider Wrapper Script erstellen
cat > /usr/local/bin/ccc-aider << 'AIDERSCRIPT'
#!/bin/bash
##########################################################
# CCC Aider Wrapper - CCC CODE Style
# Lädt Konfiguration aus Storage Root
##########################################################

source /etc/ccc.conf
AIDER_CONFIG="$STORAGE_ROOT/config/aider"

# Konfiguration laden falls vorhanden
if [ -f "$AIDER_CONFIG/aider.conf" ]; then
    source "$AIDER_CONFIG/aider.conf"
fi

# Virtual Environment aktivieren
if [ -f "$AIDER_VENV/bin/activate" ]; then
    source "$AIDER_VENV/bin/activate"
else
    echo "Aider Virtual Environment nicht gefunden in $AIDER_VENV"
    echo "Fühle aus: ccc  # um Aider zu installieren"
    exit 1
fi

# API Key Check
if [ -z "$OPENROUTER_API_KEY" ] || [ "$OPENROUTER_API_KEY" = "# Füge hier deinen OpenRouter API Key ein" ]; then
    echo "⚠️  OpenRouter API Key nicht konfiguriert!"
    echo "Bitte trage deinen API Key in $AIDER_CONFIG/openrouter-api-key ein"
    echo ""
    echo "OpenRouter API Key bekommst du unter: https://openrouter.ai/keys"
    exit 1
fi

# Aider ausführen
exec aider "\$@"
AIDERSCRIPT
chmod +x /usr/local/bin/ccc-aider

# User-friendly Symlink
ln -sf /usr/local/bin/ccc-aider /usr/local/bin/aider

# Bash Completion für Storage User
if [ -f /home/$STORAGE_USER/.bashrc ] && ! grep -q "ccc-aider" /home/$STORAGE_USER/.bashrc; then
    cat >> /home/$STORAGE_USER/.bashrc << BASHRC

# CCC Aider Integration
alias aider='ccc-aider'
export AIDER_CONFIG="$STORAGE_ROOT/config/aider"
if [ -f "\$AIDER_CONFIG/aider.conf" ]; then
    source "\$AIDER_CONFIG/aider.conf"
fi
BASHRC
fi

# Test ob Aider funktioniert
log_info "Teste Aider Installation..."
if sudo -u "$STORAGE_USER" /usr/local/bin/ccc-aider --help > /dev/null 2>&1; then
    log_success "Aider Installation erfolgreich"
    
    # Modelle auflisten (nur bei konfiguriertem API Key)
    if [ -n "$OPENROUTER_API_KEY" ] && [ "$OPENROUTER_API_KEY" != "# Füge hier deinen OpenRouter API Key ein" ]; then
        log_info "Verfügbare OpenRouter Modelle:"
        sudo -u "$STORAGE_USER" /usr/local/bin/ccc-aider --list-models openrouter/ | head -10
    fi
else
    log_warning "Aider Installation könnte Probleme haben"
fi

# Usage Information
echo ""
echo -e "${GREEN}✅ Aider Installation abgeschlossen${NC}"
echo ""
echo -e "${BLUE}Verwendung:${NC}"
echo "  aider <dateien>                    # Aider starten"
echo "  aider --model openrouter/anthropic/claude-3.5-sonnet <dateien>"
echo ""
echo -e "${YELLOW}Konfiguration:${NC}"
echo "  API Key: $AIDER_CONFIG/openrouter-api-key"
echo "  Config: $AIDER_CONFIG/aider.conf"
echo "  Virtual Env: $AIDER_DIR"
echo ""
echo -e "${GREEN}Beliebte Modelle:${NC}"
echo "  openrouter/anthropic/claude-3.5-sonnet"
echo "  openrouter/google/gemini-flash-1.5-8b"
echo "  openrouter/meta-llama/llama-3.1-8b-instruct"
echo ""

log_success "Aider installation abgeschlossen (CCC CODE Style)"
