#!/bin/bash
set -euo pipefail
##########################################################
# Ghost CMS Installation - CCC CODE Pattern
##########################################################

source /etc/ccc.conf
source /root/ccc/setup/functions.sh

echo -e "${BLUE}[MODULE]${NC} Ghost CMS Installation (CCC CODE Style)..."

# Ghost Installation Directory in Storage Root
GHOST_DIR="$STORAGE_ROOT/www/ghost"
GHOST_USER="$STORAGE_USER"
GHOST_GROUP="$STORAGE_USER"

# Ghost User ist unser Storage User (CCC CODE Pattern!)
if ! id -u "$GHOST_USER" &>/dev/null; then
    log_error "Storage User $GHOST_USER existiert nicht"
    exit 1
fi

# Ghost Directory in Storage Root erstellen
mkdir -p "$GHOST_DIR"
chown "$GHOST_USER:$GHOST_GROUP" "$GHOST_DIR"
chmod 755 "$GHOST_DIR"

# Ghost CLI installieren (global)
if ! command -v ghost &> /dev/null; then
    log_info "Installiere Ghost CLI..."
    npm install -g ghost-cli@latest
fi

# Ghost Installation prüfen
if [ -f "$GHOST_DIR/index.js" ]; then
    log_info "Ghost ist bereits installiert - Update-Modus"
    
    # Ghost Update
    cd "$GHOST_DIR"
    sudo -u "$GHOST_USER" -i -- ghost update --force
else
    log_info "Neue Ghost Installation in $GHOST_DIR..."
    
    # Prüfe Node.js-Abhängigkeit vor Installation
    if ! command -v node &> /dev/null; then
        log_error "Node.js ist nicht installiert"
        exit 1
    fi

    # Ghost installieren als Storage User (idempotent)
    cd "$GHOST_DIR"
    [ -d "content" ] && chown -R "$GHOST_USER:$GHOST_GROUP" content

    sudo -u "$GHOST_USER" -i -- <<EOF
cd "$GHOST_DIR"

# Idempotente Ghost-Installation
[ -d "versions" ] && ghost update --force || ghost install \
  --db mysql \
  --dbhost localhost \
  --dbuser "$DB_USER" \
  --dbpass "$DB_PASS" \
  --dbname "$DB_NAME" \
  --url "https://$PRIMARY_HOSTNAME" \
  --admin-url "https://$PRIMARY_HOSTNAME/ghost" \
  --ip 127.0.0.1 \
  --port 2368 \
  --process systemd \
  --no-prompt \
  --no-setup-nginx \
  --no-setup-ssl \
  --no-setup-mysql \
  --no-start

EOF

    # Ghost Systemd Service anpassen für Storage User
    if [ -f /lib/systemd/system/ghost_$(basename $GHOST_DIR).service ]; then
        sed -i "s/User=.*/User=$GHOST_USER/" /lib/systemd/system/ghost_$(basename $GHOST_DIR).service
        sed -i "s/Group=.*/Group=$GHOST_GROUP/" /lib/systemd/system/ghost_$(basename $GHOST_DIR).service
        systemctl daemon-reload
    fi
    
    # Ghost Service starten
    systemctl enable ghost_$(basename $GHOST_DIR)
    systemctl start ghost_$(basename $GHOST_DIR)
fi

# Nginx Configuration für Ghost (in Storage Root speichern)
mkdir -p "$STORAGE_ROOT/nginx/conf.d"
cat > "$STORAGE_ROOT/nginx/conf.d/ghost.conf" << 'NGINXCONF'
# Ghost CMS Configuration - Auto-generated by CCC
location / {
    proxy_pass http://127.0.0.1:2368;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Host $http_host;
    proxy_buffering off;
    proxy_redirect off;
}
NGINXCONF

log_success "Ghost CMS installation abgeschlossen (CCC CODE Style)"
