#!/bin/bash
set -euo pipefail
##########################################################
# SSL Installation - CCC CODE Pattern
##########################################################

source /etc/ccc.conf
source /root/ccc/setup/functions.sh

echo -e "${BLUE}[MODULE]${NC} SSL Installation (CCC CODE Style)..."

# Certbot installieren
if ! command -v certbot &> /dev/null; then
    log_info "Installiere Certbot..."
    apt-get install -y -qq certbot python3-certbot-nginx
fi

# SSL Verzeichnisse mit sicheren Berechtigungen erstellen
mkdir -p "$STORAGE_ROOT/ssl" && chmod 700 "$STORAGE_ROOT/ssl"
mkdir -p "$STORAGE_ROOT/nginx/ssl" && chmod 700 "$STORAGE_ROOT/nginx/ssl"

# SSL Konfiguration aktualisierbar machen
cat > "$STORAGE_ROOT/nginx/ssl/ssl.conf" << 'SSLCONF'
# SSL Configuration - Generated by CCC
ssl_certificate $STORAGE_ROOT/ssl/fullchain.pem;
ssl_certificate_key $STORAGE_ROOT/ssl/privkey.pem;
ssl_protocols TLSv1.2 TLSv1.3;
ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384;
ssl_prefer_server_ciphers off;
SSLCONF

log_info "SSL Modul bereit - Zertifikate können später mit 'certbot' erstellt werden"
log_success "SSL installation abgeschlossen"
