#!/bin/bash
set -euo pipefail
##########################################################
# SSL Installation - CCC CODE Pattern
##########################################################

source /etc/ccc.conf
source /root/ccc/setup/functions.sh

echo -e "${BLUE}[MODULE]${NC} SSL Installation (CCC CODE Style)..."

# Certbot installieren
if ! command -v certbot &> /dev/null; then
    log_info "Installiere Certbot..."
    apt-get install -y -qq certbot python3-certbot-nginx
fi

# SSL Verzeichnisse mit sicheren Berechtigungen erstellen
mkdir -p "$STORAGE_ROOT/ssl" && chmod 700 "$STORAGE_ROOT/ssl"
mkdir -p "$STORAGE_ROOT/nginx/ssl" && chmod 700 "$STORAGE_ROOT/nginx/ssl"

# SSL Konfiguration aktualisierbar machen
cat > "$STORAGE_ROOT/nginx/ssl/ssl.conf" << 'SSLCONF'
# SSL Configuration - Generated by CCC with enhanced security
ssl_certificate $STORAGE_ROOT/ssl/fullchain.pem;
ssl_certificate_key $STORAGE_ROOT/ssl/privkey.pem;
ssl_protocols TLSv1.2 TLSv1.3;
ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
ssl_prefer_server_ciphers on;
ssl_session_timeout 1d;
ssl_session_cache shared:SSL:50m;
ssl_session_tickets off;
ssl_stapling on;
ssl_stapling_verify on;
resolver 8.8.8.8 8.8.4.4 valid=300s;
resolver_timeout 5s;
add_header Strict-Transport-Security "max-age=63072000" always;
add_header X-Frame-Options DENY;
add_header X-Content-Type-Options nosniff;
add_header X-XSS-Protection "1; mode=block";
SSLCONF

log_info "SSL Modul bereit - Zertifikate können später mit 'certbot' erstellt werden"
log_success "SSL installation abgeschlossen"
